# Generated by Django 3.0.4 on 2020-03-27 09:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddrEntity',
            fields=[
                ('eid', models.UUIDField(primary_key=True, serialize=False, verbose_name='Entity Id')),
                ('e_type', models.PositiveIntegerField(choices=[(1, 'Customer'), (2, 'Delivery Agent'), (3, 'Merchant')])),
                ('profile', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('nid', models.UUIDField(primary_key=True, serialize=False, verbose_name='Notification Id')),
                ('n_type', models.PositiveIntegerField(choices=[(1, 'Sms'), (2, 'Email'), (3, 'Push (Android/iOS)')])),
                ('n_state', models.PositiveIntegerField(choices=[(1, 'Queued'), (2, 'Sent'), (3, 'Delivered'), (4, 'Read'), (5, 'Failed')])),
                ('u_cancelled', models.PositiveIntegerField(default=0)),
                ('ex_id', models.CharField(max_length=512, null=True, unique=True)),
                ('cb_info', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('eid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notification.AddrEntity')),
            ],
        ),
    ]
