# Generated by Django 3.0.4 on 2020-03-28 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='eid',
            new_name='addr_entity',
        ),
    ]
