import abc, uuid
from typing import List

from ..models import AddrEntity

class AddressableEntityABC(abc.ABC):
    @abc.abstractmethod
    def get_entity_id(self)->uuid.UUID:...
    @abc.abstractmethod
    def get_entity_type(self)->AddrEntity.AddrEntityType:...
    @abc.abstractmethod
    def get_phones(self)->List[str]:...
    @abc.abstractmethod
    def get_emails(self)->List[str]:...
    @abc.abstractmethod
    def get_fcm_tokens(self)->List[str]:...
