import abc, uuid
from typing import List


class AddressableEntityABC(abc.ABC):
    @abc.abstractmethod
    def get_entity_id(self)->uuid.UUID:...
    @abc.abstractmethod
    def get_entity_type(self)->int:...
    @abc.abstractmethod
    def get_phones(self)->List[str]:...
    @abc.abstractmethod
    def get_emails(self)->List[str]:...
    @abc.abstractmethod
    def get_fcm_tokens(self)->List[str]:...
